In [1]:
import pandas as pd

df = pd.read_csv('../data/prediction.csv')

df

   prediction  probability_class0  probability_class1     predicted_result
0   Id: 94269            0.555535            0.444465  probability class 0
1   Id: 25632            0.305192            0.694808  probability class 1
2     Id: 049            0.444644            0.555356  probability class 1
3   Id: 13397            0.495480            0.504520  probability class 1
4   Id: 58693            0.585271            0.414729  probability class 0
..        ...                 ...                 ...                  ...
95  Id: 64453            0.538294            0.461706  probability class 0
96  Id: 38683            0.490288            0.509712  probability class 1
97  Id: 53785            0.555298            0.444702  probability class 0
98  Id: 61786            0.539338            0.460662  probability class 0
99  Id: 10711            0.234184            0.765816  probability class 1

[100 rows x 4 columns]